import '../styles/globals.css';

import type { AppProps } from 'next/app';
import Footer from '../components/Footer';
import Head from 'next/head';
import Header from '../components/Header';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Solara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className='main'>
        <Component {...pageProps} />
      </main>
      <Footer/>
    </>
  )
}

export default MyApp;